name: pantab-dev
channels:
  - defaults
dependencies:
  - black
  - flake8
  - isort
  - mypy
  - pandas
  - pip
  - python
  - pytest
  - sphinx
  - pip:
    - asv
    - sphinx_rtd_theme
    - tableauhyperapi
